include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: 
    - '**/*.pb.dart'
    - '**/*.pbjson.dart'
    - '**/*.pbenum.dart'
    - '**/*.pbgrpc.dart'


custom_lint:
  rules:
    - missing_provider_scope: false
    - provider_dependencies: false
 