name: nosql_frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  protobuf: ^3.1.0
  grpc: ^3.2.3
  flutter_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.3.10
  fixnum: ^1.1.0
  flutter_quill: ^7.4.4
  json_editor_flutter: ^1.0.1
  flutter_json_view: ^1.1.3
  rxdart: ^0.27.7
  flutter_secure_storage: ^9.0.0
  flutter_login: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint:
  riverpod_lint:
  build_runner:
  riverpod_generator:
  dart_mappable_builder: ^3.2.1

flutter:
  uses-material-design: true
